import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Briefcase, Crown, Eye, Plus, ShieldCheck, Trash2, UserPlus, Users, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../utils/api";
import CorporatePasswordField from "../components/CorporatePasswordField";

const emptyTeam = { name: "", department: "", description: "" };
const emptyPerson = { name: "", email: "", designation: "", skills: "", password: "" };
const TEAM_IMAGES = {
  engineering: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&h=620&fit=crop",
  "data science": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000&h=620&fit=crop",
  marketing: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1000&h=620&fit=crop",
  sales: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1000&h=620&fit=crop",
  finance: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1000&h=620&fit=crop",
  hr: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1000&h=620&fit=crop",
  operations: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1000&h=620&fit=crop",
  general: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1000&h=620&fit=crop",
};
const teamImage = (team) => TEAM_IMAGES[String(team.department || "general").toLowerCase()] || TEAM_IMAGES.general;
const errorMessage = (error, fallback) => error?.response?.data?.message || fallback;

export default function CompanyRoles() {
  const navigate = useNavigate();
  const [teams, setTeams] = useState([]);
  const [metrics, setMetrics] = useState({ totalTeams: 0, leadersAssigned: 0, teamMembers: 0, unassignedEmployees: 0 });
  const [selectedId, setSelectedId] = useState(null);
  const [modal, setModal] = useState(null);
  const [teamForm, setTeamForm] = useState(emptyTeam);
  const [personForm, setPersonForm] = useState(emptyPerson);
  const [notice, setNotice] = useState(null);
  const [working, setWorking] = useState(false);
  const [loading, setLoading] = useState(true);
  const selectedTeam = useMemo(() => teams.find((team) => team.id === selectedId), [teams, selectedId]);

  const loadTeams = useCallback(async () => {
    try {
      const { data } = await api.get("/company/teams");
      setTeams(data.teams || []); setMetrics(data.metrics || {});
    } catch (error) { setNotice({ tone: "error", text: errorMessage(error, "Unable to load company teams.") }); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { loadTeams(); }, [loadTeams]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(null), 4800); return () => clearTimeout(timer); }, [notice]);

  const openPersonModal = (type, team) => {
    setPersonForm(type === "leader" && team.leader ? { name: team.leader.name || "", email: team.leader.email || "", designation: team.leader.designation || "", skills: (team.leader.skills || []).join(", "), password: "" } : emptyPerson);
    setModal({ type, team });
  };
  const createTeam = async (event) => { event.preventDefault(); setWorking(true); try { const { data } = await api.post("/company/teams", teamForm); setTeamForm(emptyTeam); setModal(null); setSelectedId(data.team?.id || null); setNotice({ tone: "success", text: "Team created. Open it to appoint a leader and add members." }); await loadTeams(); } catch (error) { setNotice({ tone: "error", text: errorMessage(error, "Unable to create this team.") }); } finally { setWorking(false); } };
  const savePerson = async (event) => { event.preventDefault(); setWorking(true); try { const payload = { ...personForm, skills: personForm.skills.split(",").map((item) => item.trim()).filter(Boolean) }; const endpoint = `/company/teams/${modal.team.id}/${modal.type === "leader" ? "leader" : "members"}`; const response = modal.type === "leader" ? await api.put(endpoint, payload) : await api.post(endpoint, payload); const delivery = response.data.notification?.status || "queued"; setModal(null); setPersonForm(emptyPerson); setNotice({ tone: delivery === "failed" ? "warning" : "success", text: `${modal.type === "leader" ? "Leader appointed" : "Member onboarded"}. Email notification ${delivery}.` }); await loadTeams(); } catch (error) { setNotice({ tone: "error", text: errorMessage(error, "Unable to save this company role.") }); } finally { setWorking(false); } };
  const deleteTeam = async (team) => { if (!window.confirm(`Delete ${team.name}? Its employee accounts will be kept as unassigned.`)) return; try { await api.delete(`/company/teams/${team.id}`); setSelectedId(null); await loadTeams(); setNotice({ tone: "success", text: `${team.name} was deleted; employee accounts were preserved.` }); } catch (error) { setNotice({ tone: "error", text: errorMessage(error, "Unable to delete this team.") }); } };
  const deleteMember = async (member) => { if (!window.confirm(`Remove ${member.name} and delete their corporate employee record?`)) return; try { await api.delete(`/employees/${member.id}`); await loadTeams(); setNotice({ tone: "success", text: `${member.name} was removed from the company.` }); } catch (error) { setNotice({ tone: "error", text: errorMessage(error, "Unable to remove this member.") }); } };

  const metricCards = [["Total Teams", metrics.totalTeams || 0, Briefcase, "blue"], ["Leaders Assigned", metrics.leadersAssigned || 0, Crown, "purple"], ["Team Members", metrics.teamMembers || 0, Users, "green"], ["Unassigned People", metrics.unassignedEmployees || 0, UserPlus, "orange"]];

  return <div className="employer-page company-roles-page"><div className="employer-shell">
    {!selectedTeam ? <>
      <header className="employer-page-header"><div><button type="button" className="employer-back-link" onClick={() => navigate("/employee-management")}><ArrowLeft /> Back to Team Management</button><span className="employer-eyebrow">Company workspace</span><h1>Teams built for momentum</h1><p>Enter a team to manage its leader, members, learning and permissions.</p></div><button type="button" className="employer-button employer-button-blue" onClick={() => setModal({ type: "team" })}><Plus /> Create Team</button></header>
      <section className="employer-metric-grid company-role-metrics">{metricCards.map(([label, value, Icon, tone]) => <article key={label} className={`employer-metric-card tone-${tone}`}><div><span>{label}</span><strong>{value}</strong></div><i><Icon /></i></article>)}</section>
      <section className="company-access-map employer-panel"><header><div><span>Permission map</span><h2>One company, focused workspaces</h2></div><p>Access follows each corporate email mapping.</p></header><div><article className="tone-blue"><i><ShieldCheck /></i><span><small>Full company access</small><strong>Employer Head</strong><em>All teams, courses and reports</em></span></article><ArrowRight className="company-access-arrow"/><article className="tone-purple"><i><Crown /></i><span><small>{metrics.leadersAssigned || 0} active leader(s)</small><strong>Team Leaders</strong><em>Their team only</em></span></article><ArrowRight className="company-access-arrow"/><article className="tone-green"><i><Users /></i><span><small>{metrics.teamMembers || 0} learner(s)</small><strong>Members</strong><em>Personal learning dashboard</em></span></article></div></section>
      <section className="employer-panel company-role-panel"><div className="employer-panel-heading"><div><span>Click a workspace to enter</span><h2>Company Teams</h2></div><small>Management happens inside each team</small></div><div className="company-team-grid visual-team-grid">{teams.map((team) => <button type="button" className="visual-team-card" key={team.id} onClick={() => setSelectedId(team.id)}><img src={teamImage(team)} alt={`${team.name} team`} /><span className="visual-team-shade"/><div className="visual-team-copy"><small>{team.department}</small><h3>{team.name}</h3><p>{team.description || "A focused team workspace"}</p><dl><div><dt>Members</dt><dd>{team.memberCount || 0}</dd></div><div><dt>Leader</dt><dd>{team.leader ? "Ready" : "Open"}</dd></div><div><dt>Progress</dt><dd>{team.avgCompletion || 0}%</dd></div></dl><em>Enter team <ArrowRight /></em></div></button>)}</div>{loading && <div className="employer-empty-state">Loading company teams...</div>}{!loading && !teams.length && <div className="employer-empty-state">No teams yet. Create your first department workspace.</div>}</section>
    </> : <>
      <header className="team-workspace-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(9,25,65,.94),rgba(30,44,106,.76),rgba(41,25,82,.38)),url(${teamImage(selectedTeam)})` }}><button type="button" onClick={() => setSelectedId(null)}><ArrowLeft /> All company teams</button><div><span>{selectedTeam.department} workspace</span><h1>{selectedTeam.name}</h1><p>{selectedTeam.description || "Manage this team's people, leadership and learning."}</p></div><dl><div><dt>Members</dt><dd>{selectedTeam.memberCount || 0}</dd></div><div><dt>Active</dt><dd>{selectedTeam.activeMembers || 0}</dd></div><div><dt>Avg. progress</dt><dd>{selectedTeam.avgCompletion || 0}%</dd></div></dl></header>
      <section className="team-workspace-actions"><button onClick={() => openPersonModal("leader", selectedTeam)}><Crown/><span><strong>{selectedTeam.leader ? "Change team leader" : "Appoint team leader"}</strong><small>Map their corporate login and notify them</small></span></button><button onClick={() => openPersonModal("member", selectedTeam)}><UserPlus/><span><strong>Add team member</strong><small>Create credentials and send onboarding email</small></span></button><button onClick={() => navigate("/courses")}><BookOpen/><span><strong>Browse course library</strong><small>Find learning to assign to this team</small></span></button><button className="danger" onClick={() => deleteTeam(selectedTeam)}><Trash2/><span><strong>Delete team</strong><small>Accounts become unassigned</small></span></button></section>
      <section className="employer-panel team-workspace-leader"><div className="team-workspace-section-title"><div><span>Team head</span><h2>Leadership</h2></div></div>{selectedTeam.leader ? <article><i><Crown/></i><div><strong>{selectedTeam.leader.name}</strong><span>{selectedTeam.leader.designation || `Leader of ${selectedTeam.department}`}</span><small>{selectedTeam.leader.email}</small></div><button onClick={() => navigate(`/employee/${selectedTeam.leader.id}`)}><Eye/> View profile</button><button onClick={() => navigate(`/assign-courses/${selectedTeam.leader.id}`)}><BookOpen/> Assign courses</button></article> : <div className="employer-empty-state">No leader yet. Appoint a leader to activate their department dashboard.</div>}</section>
      <section className="employer-panel team-workspace-members"><div className="team-workspace-section-title"><div><span>{selectedTeam.memberCount || 0} people</span><h2>Team Members</h2></div><button className="employer-button employer-button-blue" onClick={() => openPersonModal("member", selectedTeam)}><Plus/> Add member</button></div><div className="employer-table-scroll"><table><thead><tr><th>Employee</th><th>Role</th><th>Assigned</th><th>Completed</th><th>Progress</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(selectedTeam.members || []).map((member) => <tr key={member.id}><td><strong>{member.name}</strong><span>{member.email}</span></td><td>{member.designation || "Corporate Employee"}</td><td>{member.assignedCourses || 0}</td><td>{member.completedCourses || 0}</td><td><div className="employer-table-progress"><i><span style={{width:`${member.progress || 0}%`}}/></i><small>{member.progress || 0}%</small></div></td><td><em className={`status-${member.status}`}>{member.status}</em></td><td><div className="employer-row-actions"><button onClick={() => navigate(`/employee/${member.id}`)}>View</button><button onClick={() => navigate(`/assign-courses/${member.id}`)}>Assign</button><button className="employer-action-delete" onClick={() => deleteMember(member)}><Trash2/> Delete</button></div></td></tr>)}</tbody></table></div>{!(selectedTeam.members || []).length && <div className="employer-empty-state">No members yet. Add the first person to this team.</div>}</section>
    </>}
  </div>{notice && <div className={`employer-toast tone-${notice.tone}`} role="status">{notice.text}</div>}
  {modal?.type === "team" && <div className="employer-modal-layer" onMouseDown={(event) => event.target === event.currentTarget && setModal(null)}><section className="employer-modal" role="dialog" aria-modal="true"><header><div><span>Company structure</span><h2>Create New Team</h2></div><button type="button" onClick={() => setModal(null)}><X/></button></header><form onSubmit={createTeam}><input placeholder="Team name" value={teamForm.name} onChange={(event) => setTeamForm({...teamForm,name:event.target.value})} required autoFocus/><select value={teamForm.department} onChange={(event) => setTeamForm({...teamForm,department:event.target.value})} required><option value="">Select department</option>{Object.keys(TEAM_IMAGES).map((item) => <option key={item}>{item.replace(/\b\w/g,(letter)=>letter.toUpperCase())}</option>)}</select><textarea rows="3" placeholder="Team mission (optional)" value={teamForm.description} onChange={(event) => setTeamForm({...teamForm,description:event.target.value})}/><footer><button className="employer-button employer-button-blue" disabled={working}>{working?"Creating...":"Create Team"}</button><button type="button" className="employer-button employer-button-muted" onClick={() => setModal(null)}>Cancel</button></footer></form></section></div>}
  {["leader","member"].includes(modal?.type) && <div className="employer-modal-layer" onMouseDown={(event) => event.target === event.currentTarget && setModal(null)}><section className="employer-modal" role="dialog" aria-modal="true"><header><div><span>{modal.team.name} · {modal.team.department}</span><h2>{modal.type === "leader" ? "Assign Team Leader" : "Add Team Member"}</h2></div><button type="button" onClick={() => setModal(null)}><X/></button></header><form onSubmit={savePerson}><input placeholder="Full name" value={personForm.name} onChange={(event)=>setPersonForm({...personForm,name:event.target.value})} required autoFocus/><input type="email" placeholder="Corporate email" value={personForm.email} onChange={(event)=>setPersonForm({...personForm,email:event.target.value})} required/><CorporatePasswordField value={personForm.password} onChange={(password)=>setPersonForm({...personForm,password})} label={modal.type === "leader" ? "Team leader WEL.X password" : "Team member WEL.X password"}/><input placeholder={modal.type === "leader" ? "Leadership title (optional)" : "Job title (optional)"} value={personForm.designation} onChange={(event)=>setPersonForm({...personForm,designation:event.target.value})}/><input placeholder="Skills (comma separated)" value={personForm.skills} onChange={(event)=>setPersonForm({...personForm,skills:event.target.value})}/><p className="company-modal-note"><ShieldCheck/>This login is mapped directly to the {modal.type === "leader" ? "leader" : "employee"} workspace and emailed securely.</p><footer><button className={`employer-button ${modal.type === "leader" ? "employer-button-purple":"employer-button-blue"}`} disabled={working}>{working?"Saving...":modal.type === "leader"?"Assign & Notify":"Add & Send Credentials"}</button><button type="button" className="employer-button employer-button-muted" onClick={() => setModal(null)}>Cancel</button></footer></form></section></div>}
  </div>;
}
