import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowLeft, BookOpen, Check, Clock, Layers as Layers3, Search, Sparkles, Star, Users, X } from "lucide-react";
import { useCurrency } from "../contexts/CurrencyContext";
import api from "../utils/api";

export default function CourseMarketplace() {
  const [params] = useSearchParams(); const navigate = useNavigate();
  const phaseKey = params.get("customizePhase"); const returnTo = params.get("returnTo") || "/learning-roadmap";
  const [searchTerm,setSearchTerm]=useState(""); const [selectedCategory,setSelectedCategory]=useState("all"); const [selectedLevel,setSelectedLevel]=useState("all"); const [courses,setCourses]=useState([]); const [selected,setSelected]=useState([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const { formatPrice } = useCurrency();
  useEffect(()=>{(async()=>{try{const [{data:courseData},{data:pathData}] = await Promise.all([api.get("/courses"), phaseKey ? api.get("/career-path") : Promise.resolve({data:null})]); setCourses(Array.isArray(courseData)?courseData:[]); if(pathData){const phase=pathData.careerPath.phases.find((item)=>item.key===phaseKey); setSelected((phase?.courses||[]).map((course)=>course._id));}}catch(requestError){setError(requestError?.response?.data?.message||"Courses could not be loaded.");}})();},[phaseKey]);
  const categories=useMemo(()=>["all",...new Set(courses.map((course)=>course.category||"General"))],[courses]);
  const filtered=courses.filter((course)=>{const needle=searchTerm.toLowerCase();return(!needle||[course.title,course.description,course.category,...(course.skills||[])].join(" ").toLowerCase().includes(needle))&&(selectedCategory==="all"||course.category===selectedCategory)&&(selectedLevel==="all"||String(course.level).toLowerCase()===selectedLevel);});
  const toggle=(id)=>{setError("");setSelected((current)=>current.includes(id)?current.filter((item)=>item!==id):current.length>=3?(setError("Each phase can contain a maximum of 3 courses."),current):[...current,id]);};
  const save=async()=>{if(!selected.length){setError("Select at least one course for this phase.");return;}setSaving(true);try{await api.put(`/career-path/phases/${phaseKey}`,{courseIds:selected});navigate(returnTo);}catch(requestError){setError(requestError?.response?.data?.message||"This phase could not be saved.");}finally{setSaving(false);}};
  return <div className={`welx-inner-page welx-courses-page ${phaseKey?"is-phase-builder":""}`}>
    <div className="welx-inner-glow welx-inner-glow-one"/><div className="welx-inner-glow welx-inner-glow-two"/>
    <header className="welx-inner-hero"><div className="welx-inner-shell welx-inner-hero-grid"><div>{phaseKey?<button className="market-builder-back" onClick={()=>navigate(returnTo)}><ArrowLeft/> Back to career path</button>:<nav className="welx-breadcrumbs"><Link to="/">Home</Link><span>/</span><b>Courses</b></nav>}<p className="welx-inner-kicker">{phaseKey?"Phase customization studio":"Find your next capability"}</p><h1>{phaseKey?<>Make this phase <em>uniquely yours.</em></>:<>Courses that turn curiosity into <em>momentum.</em></>}</h1><p>{phaseKey?"Choose up to three live marketplace courses. Mix technology, business, finance and people skills.":"Explore practical learning across technology, business, creativity, leadership, and career growth."}</p></div><div className="welx-course-hero-orbit"><span>{phaseKey?<Layers3/>:<BookOpen/>}</span><i/><i/><i/><strong>{phaseKey?<>Choose<br/>Mix<br/>Build</>:<>Learn<br/>Practice<br/>Grow</>}</strong></div></div></header>
    <main className="welx-inner-shell welx-course-content"><section className="welx-course-filters"><div className="welx-course-search"><Search/><input placeholder="Search courses, skills, or topics..." value={searchTerm} onChange={(e)=>setSearchTerm(e.target.value)}/></div><div className="welx-filter-field"><label>Category</label><select value={selectedCategory} onChange={(e)=>setSelectedCategory(e.target.value)}>{categories.map((category)=><option key={category} value={category}>{category==="all"?"All Categories":category}</option>)}</select></div><div className="welx-filter-field"><label>Level</label><select value={selectedLevel} onChange={(e)=>setSelectedLevel(e.target.value)}>{["all","beginner","intermediate","advanced"].map((level)=><option key={level}>{level==="all"?"All Levels":level[0].toUpperCase()+level.slice(1)}</option>)}</select></div></section>
      {error&&<div className="market-builder-error">{error}</div>}<div className="welx-course-results"><span>{filtered.length}</span> marketplace courses {phaseKey&&<b>· {selected.length}/3 selected</b>}</div>
      <section className="welx-course-grid">{filtered.map((course)=>{const chosen=selected.includes(course._id);return <article key={course._id} className={`welx-course-card ${chosen?"is-builder-selected":""}`}><div className="welx-course-image"><img src={course.image||"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=460&fit=crop"} alt={course.title}/><span>{course.category||"WEL.X course"}</span>{phaseKey&&<button onClick={()=>toggle(course._id)} aria-label={`${chosen?"Remove":"Add"} ${course.title}`}>{chosen?<Check/>:<Sparkles/>}</button>}</div><div className="welx-course-card-body"><div className="welx-course-card-meta"><span className={`is-${course.level||"all"}`}>{course.level||"All levels"}</span><span><Star/> {course.rating||"N/A"}</span></div><h2>{course.title}</h2><p>by {course.instructor||"WEL.X faculty"}</p><div className="welx-course-facts"><span><Users/> {course.students||0}</span><span><Clock/> {course.duration||"Self paced"}</span></div><footer><strong>{formatPrice(course.price||0)}</strong>{phaseKey?<button onClick={()=>toggle(course._id)}>{chosen?<><X/> Remove</>:<><Check/> Add to phase</>}</button>:<Link to={`/course/${course._id}`}>View course <span>↗</span></Link>}</footer></div></article>;})}</section>
      {!filtered.length&&<div className="welx-course-empty"><BookOpen/><h2>No courses found</h2><p>Try adjusting your search or filters.</p></div>}
    </main>
    {phaseKey&&<aside className="market-builder-tray"><div><Layers3/><span><strong>Phase bundle builder</strong><small>{selected.length?`${selected.length} selected · ${3-selected.length} slot${3-selected.length===1?"":"s"} left`:"Choose up to 3 courses"}</small></span></div><div className="market-builder-dots">{[0,1,2].map((index)=><i key={index} className={index<selected.length?"is-filled":""}/>)}</div><button onClick={save} disabled={saving||!selected.length}>{saving?"Saving phase…":"Save customized phase"}<Check/></button></aside>}
  </div>;
}
