import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Check, CreditCard, Layers as Layers3, Lock, ShieldCheck } from "lucide-react";
import { loadStripe } from "@stripe/stripe-js";
import { CardCvcElement, CardExpiryElement, CardNumberElement, Elements, useElements, useStripe } from "@stripe/react-stripe-js";
import { useCurrency } from "../contexts/CurrencyContext";
import api from "../utils/api";
import { paymentAPI } from "../utils/enhancedApiUpdated";

const stripePromise = loadStripe(import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY || "pk_test_placeholder");

function CheckoutForm({ user, courses, purchase, formatPrice, total }) {
  const stripe=useStripe(); const elements=useElements(); const navigate=useNavigate();
  const [complete,setComplete]=useState({number:false,expiry:false,cvc:false}); const [processing,setProcessing]=useState(false); const [error,setError]=useState("");
  const submit=async(event)=>{event.preventDefault();if(!stripe||!elements||!Object.values(complete).every(Boolean)||processing)return;if(!user){navigate("/login");return;}setProcessing(true);setError("");try{const {data}=await paymentAPI.createPaymentIntent(purchase);const result=await stripe.confirmCardPayment(data.clientSecret,{payment_method:{card:elements.getElement(CardNumberElement)}});const response=await paymentAPI.updatePaymentStatus({id:data.id,paymentId:data.paymentId,result});if(response.data.status!=="SUCCESS")throw new Error(response.data.message||"Payment failed");navigate(purchase.purchaseType==="phase_bundle"?"/learning-roadmap":`/course/${courses[0]._id}`);}catch(requestError){setError(requestError?.response?.data?.message||requestError.message||"Payment could not be completed.");}finally{setProcessing(false);}};
  return <form onSubmit={submit} className="space-y-6"><label className="block text-sm font-medium text-gray-700">Receipt email<input type="email" defaultValue={user?.email||""} className="w-full p-3 mt-2 border border-gray-300 rounded-lg" required/></label><div className="flex items-center"><CreditCard className="w-5 h-5 mr-2"/><strong>Credit / debit card</strong></div><label className="block text-sm font-medium text-gray-700">Card number<div className="w-full p-3 mt-2 border border-gray-300 rounded-lg"><CardNumberElement onChange={(event)=>setComplete((value)=>({...value,number:event.complete}))}/></div></label><div className="grid grid-cols-2 gap-4"><label className="block text-sm font-medium text-gray-700">Expiry<div className="w-full p-3 mt-2 border border-gray-300 rounded-lg"><CardExpiryElement onChange={(event)=>setComplete((value)=>({...value,expiry:event.complete}))}/></div></label><label className="block text-sm font-medium text-gray-700">CVC<div className="w-full p-3 mt-2 border border-gray-300 rounded-lg"><CardCvcElement onChange={(event)=>setComplete((value)=>({...value,cvc:event.complete}))}/></div></label></div>{error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-3 text-sm">{error}</div>}<button className="w-full btn-primary" disabled={processing||!Object.values(complete).every(Boolean)}>{processing?"Processing securely…":`Complete purchase · ${formatPrice(total)}`}</button></form>;
}

export default function Payment({user}){
  const [params]=useSearchParams();const navigate=useNavigate();const {formatPrice}=useCurrency();const [courses,setCourses]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const purchaseType=params.get("type")==="phase_bundle"?"phase_bundle":"single";const phaseKey=params.get("phaseId")||"";const ids=useMemo(()=>[...new Set((params.get("courseIds")||params.get("courseId")||"").split(",").filter(Boolean))],[params]);
  useEffect(()=>{if(!ids.length){navigate("/courses");return;}(async()=>{try{const responses=await Promise.all(ids.map((id)=>api.get(`/courses/${id}`)));setCourses(responses.map((response)=>response.data));}catch(requestError){setError(requestError?.response?.data?.message||"Course details could not be loaded.");}finally{setLoading(false);}})();},[ids.join(","),navigate]);
  const subtotal=courses.reduce((sum,course)=>sum+Number(course.price||0),0);const discount=purchaseType==="phase_bundle"&&courses.length>1?subtotal*.2:0;const total=Math.round((subtotal-discount)*100)/100;const purchase={courseIds:ids,purchaseType,phaseKey};
  if(loading)return <div className="max-w-4xl mx-auto px-4 py-16 text-center">Preparing secure checkout…</div>;if(error)return <div className="max-w-4xl mx-auto px-4 py-16"><div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">{error}</div></div>;
  return <main className="max-w-5xl mx-auto px-4 py-10"><header className="mb-8"><span className="text-sm font-bold text-blue-700 flex items-center gap-2"><ShieldCheck className="w-4 h-4"/> Secure WEL.X checkout</span><h1 className="text-3xl font-bold mt-2">{purchaseType==="phase_bundle"?"Unlock your complete phase":"Complete your purchase"}</h1><p className="text-gray-500 mt-2">Access is attached to your account immediately after payment.</p></header><div className="grid lg:grid-cols-2 gap-8"><section className="card"><div className="flex items-center mb-6"><Lock className="w-5 h-5 text-green-600 mr-2"/><span className="text-sm text-gray-600">Encrypted payment</span></div><Elements stripe={stripePromise}><CheckoutForm user={user} courses={courses} purchase={purchase} formatPrice={formatPrice} total={total}/></Elements></section><aside className="card"><div className="flex items-center justify-between mb-5"><h2 className="text-xl font-semibold">Order summary</h2>{purchaseType==="phase_bundle"&&<span className="px-3 py-1 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex items-center gap-1"><Layers3 className="w-3 h-3"/> Phase bundle</span>}</div><div className="space-y-3">{courses.map((course)=><article key={course._id} className="flex gap-3 p-3 rounded-xl bg-gray-50"><img src={course.image} alt="" className="w-16 h-16 object-cover rounded-lg"/><div className="flex-1"><strong className="text-sm block">{course.title}</strong><small className="text-gray-500">{course.category} · {course.duration}</small><b className="block text-sm text-blue-700 mt-1">{formatPrice(course.price)}</b></div></article>)}</div><div className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div>{discount>0&&<><div className="flex justify-between text-green-700 font-semibold"><span>Complete phase discount (20%)</span><span>−{formatPrice(discount)}</span></div><p className="p-3 rounded-lg bg-green-50 text-green-700 text-xs">The 20% saving applies because these courses are being purchased together as one phase. It does not apply to individual course purchases.</p></>}<div className="flex justify-between border-t pt-3 text-lg font-bold"><span>Total</span><span>{formatPrice(total)}</span></div></div><ul className="mt-6 p-4 rounded-xl bg-blue-50 text-blue-700 text-sm space-y-2"><li className="flex gap-2"><Check className="w-4 h-4"/> Immediate account access</li><li className="flex gap-2"><Check className="w-4 h-4"/> Real-time progress tracking</li><li className="flex gap-2"><Check className="w-4 h-4"/> Completion certificate where enabled</li></ul></aside></div></main>;
}
